"""Render a SLURM submission for a planned sweep: one dependent job array per wave.

Run from this directory, after ``nanopnp sweep plan ... --directory phase1``::

    python render_slurm.py phase1/plan.json --workdir ../.. --store store --out phase1.sh

It writes two files: ``<out>``, a shell script that submits each wave as a job
array depending on the previous one, and ``<out stem>.member.sbatch``, the job every
array element runs: ``nanopnp sweep run <plan> --index $SLURM_ARRAY_TASK_ID``. Nothing
here talks to a scheduler, and nanopnp ships no scheduler library (CON-07): the
wave ranges ``nanopnp sweep plan`` prints are the whole integration, and this
script is two loops over them. Review both files, set the account and partition
your cluster needs, then run ``bash <out>`` on the login node.

Why ``afterany`` and not ``afterok``: a member that fails to converge at a hard
corner of the envelope is an expected *result* (the IF-02 exit NOTE), not a broken
dispatch, and its children fall back to the full continuation ladder and record
why. ``afterok`` would cancel the rest of the sweep over one corner.
"""

from __future__ import annotations

import argparse
import json
import logging
import shlex
from pathlib import Path

log = logging.getLogger("render_slurm")

MEMBER = """#!/bin/bash
#SBATCH --job-name={name}
#SBATCH --chdir={workdir}
#SBATCH --cpus-per-task=1
#SBATCH --time={time}
#SBATCH --output={logs}/%x-%A_%a.out
# One member of the sweep: its own exit code is the job's (the IF-02 exit NOTE).
export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1
exec nanopnp sweep run {plan} --store {store} --index "$SLURM_ARRAY_TASK_ID"
"""


def render(
    plan_path: Path,
    *,
    workdir: Path,
    store: Path,
    out: Path,
    time: str,
    concurrency: int,
) -> tuple[Path, Path]:
    """Write the submission script and the member job; return both paths."""
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    waves: list[list[int]] = plan["waves"]
    name = plan["name"]
    member = out.with_suffix(".member.sbatch")
    logs = workdir / "slurm-logs"
    member.write_text(
        MEMBER.format(
            name=name,
            workdir=shlex.quote(str(workdir)),
            time=time,
            logs=shlex.quote(str(logs)),
            plan=shlex.quote(str(plan_path.resolve())),
            store=shlex.quote(str(store.resolve())),
        ),
        encoding="utf-8",
    )
    lines = [
        "#!/bin/bash",
        f"# Submit sweep {name!r} ({len(plan['points'])} points) as {len(waves)} dependent",
        "# job arrays, one per wave. Generated by render_slurm.py; review before running.",
        "set -euo pipefail",
        f"mkdir -p {shlex.quote(str(logs))}",
        "previous=",
    ]
    for wave, (first, last) in enumerate(waves):
        span = f"{first}-{last - 1}%{concurrency}"
        lines += [
            f"# wave {wave}: {last - first} point(s)",
            f"previous=$(sbatch --parsable --array={span} "
            f"${{previous:+--dependency=afterany:$previous}} {shlex.quote(str(member))})",
        ]
    lines.append('echo "submitted; the last wave is job $previous"')
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out, member


def main() -> None:
    """Parse the command line and render."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("plan", type=Path, help="the plan.json that 'nanopnp sweep plan' wrote")
    parser.add_argument(
        "--workdir",
        type=Path,
        required=True,
        help="directory the members run in; case paths resolve against it",
    )
    parser.add_argument("--store", type=Path, required=True, help="the artefact store")
    parser.add_argument("--out", type=Path, required=True, help="the submission script")
    parser.add_argument("--time", default="02:00:00", help="wall-clock limit per member")
    parser.add_argument(
        "--concurrency", type=int, default=64, help="array elements running at once"
    )
    args = parser.parse_args()
    out, member = render(
        args.plan,
        workdir=args.workdir.resolve(),
        store=args.store,
        out=args.out,
        time=args.time,
        concurrency=args.concurrency,
    )
    log.info("wrote %s and %s", out, member)


if __name__ == "__main__":
    main()
